### ISSUE TITLE
Application Pattern

### ISSUE THREAD

**Issue by FarshidABZ** [mohsenoid/Rick-and-Morty#7]
Is there any reason to use MVP? There some other patterns like MVVM and MVI, why you have used MVP for this project?

**Comment by mohsenoid** [comment]
It is just a learning material and MVP was the simplest to apply.
I will soon apply Room instead of pure SQLite and later will create a branch for the Android Architecture Component.

**Comment by mohsenoid** [comment]
@FarshidABZ feel free to fork and create your own branch using whatever you like ;)
